[package]
name = "tornet-rust"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["socks", "blocking"] }
clap = { version = "4.5.32", features = ["derive"] }
signal-hook = "0.3.17"
colored = "3"
